name: 'DemoJSAction'
description: 'Display massage'
inputs:
  name-of-you:  # id of input
    description: 'Your name'
    required: true
    default: 'Marija'
outputs:
  time: # id of output
    description: 'The time of the message'
runs:
  using: 'node12'
  main: 'dist/index.js' # TODO sta mu je ovaj dist/index.js file mnogo je dug i razlikuje se od index.js koji sam ja napisalal